name: Deploy via Flux

on:
  workflow_dispatch:
    inputs:
      namespace:
        type: choice
        description: 'Select namespace'
        options:
        - s01-classroom-foxford
        - s01-minigroup-foxford
        - s01-webinar-foxford
        - s01-webinar-b2g
        - t01
        - t02
        - t03
      version:
        description: 'Commit/tag/branch'
        required: false
        default: 'master'

jobs:
  deploy:
    uses: foxford/reusable-workflows/.github/workflows/deploy-via-flux.yml@master
    with:
      namespace: ${{ inputs.namespace }}
      version: ${{ inputs.version }}
    secrets:
      kube_config_base64: ${{ secrets.KUBE_CONFIG_DEV_BASE64 }} 
      gh_token: ${{ secrets._GITHUB_TOKEN }}

